.PHONY: clean All

All:
	@echo "----------Building project:[ Server_kr_app - Debug ]----------"
	@"$(MAKE)" -f  "Server_kr_app.mk"
clean:
	@echo "----------Cleaning project:[ Server_kr_app - Debug ]----------"
	@"$(MAKE)" -f  "Server_kr_app.mk" clean
